exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "__init__.py",
]

[lint]
select = [
    "I", # Isort
]
fixable = ["ALL"]
unfixable = ["F401"]

[lint.isort]
lines-after-imports = 2
combine-as-imports = true
force-sort-within-sections = true

[format]
quote-style = "double"

line-ending = "auto"

